name: test_custom_lint
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  # args: ^2.6.0
  # collection: ^1.18.0
  custom_lint: ^0.7.0
  custom_lint_builder: ^0.7.0
  # path: ^1.9.1
  # tint: ^2.0.1
  # yaml: ^3.1.3
